# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: enabled
dist: trusty
cache:
  - packages
  - ccache
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'

    packages:
      - libproj-dev
#      - libgeos-dev
#      - libspatialite-dev
#      - libgdal-dev
#      - gdal-bin

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env:
           - BUILD_NAME=trusty_release
           - R_CODECOV=true
        - os: linux
          r: devel
          dist: trusty
        - os: linux
          r: oldrel
          dist: trusty
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
          env:
           - BUILD_NAME=osx_release
           - R_CODECOV=true

after_success:
  - Rscript -e 'covr::codecov()'